# Generated by Django 3.1.3 on 2020-12-06 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='enseignant',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.enseignant'),
            preserve_default=False,
        ),
    ]
